### ISSUE TITLE
'WhispersyncClient.getGameData()' on a null object reference (NullPointerException)

### ISSUE THREAD

**Issue by Detor** [xsellier/godotamazon#1]
When I call `godot_amazon.amazon_initialize(get_instance_ID)` the game just crashes, i made sure the api_key.txt was at the right place, 'GodotAmazon' module was added, and the custom templates were added, but the game just crashes

picture shows amazon.gd which gets autoloaded

![screenshot from 2018-06-04 21-32-31](https://user-images.githubusercontent.com/17194678/40940157-d2a773f4-683e-11e8-820e-5f0256a4f42b.png)

**Comment by xsellier** [comment]
May you post the result of the following command on pastebin and posting the link here:

`adb logcat godot:* GodotAmazon:* InAppManager:* InAppPurchasingListener:* GameCircleAchievements:* GameCircleAuthentication:* GameCircleClient:* GameCircleLeaderboards:* GameCircleSnapshot:* *:S DEBUG:* AndroidRuntime:V ValidateServiceOp:V`

**Comment by Detor** [comment]
how do use it in the terminal?

**Comment by Detor** [comment]
Do you mean this?

[godot_adblogcat_amazon.txt](https://github.com/binogure-studio/godotamazon/files/2069900/godot_adblogcat_amazon.txt)

**Comment by xsellier** [comment]
It seems the Amazon SDK is not properly initialized.

You need to put `api_key.txt` in the same directory of `export.cfg`.
Also when you export the game you need to include the `api_key.txt`, or to include `*.txt` (if it is not working).

![image](https://user-images.githubusercontent.com/6616005/40941096-d3d6ed9e-6817-11e8-9b16-e98bee43da3b.png)

**Comment by xsellier** [comment]
@Detor Please tell me if you keep having the same issue.

**Comment by Detor** [comment]
The `api_key.txt` was always in the same directory as the `export.cfg` and I already had the `*.txt` filter included but it seems to still crash

![screenshot_2018-06-04-23-50-23](https://user-images.githubusercontent.com/17194678/40945952-854f4864-684a-11e8-9cec-d231b9e9b75b.png)

**Comment by xsellier** [comment]
@Detor Have you modified the [`ids.xml` file](https://github.com/binogure-studio/godotamazon#amazon-in-app-purchase)?

Replace `YOUR APPLICATION ID HERE` by `com.dsguy.dodgeitlegacy` (I assume it is the name of your game)

Also, you need to have created your app in amazon before starting using their SDK.

**Comment by Detor** [comment]
I just finished trying it again recompiling but with my app id, it still crashed, i even tried recompiling with the developer publishing app id amazon gave my app and it still crashed

Oh and btw I'm using Godot v2.1.4-stable and I built the custom template with the Godot v2.1.4-stable source code

**Comment by xsellier** [comment]
@Detor It works with Godot Engine 2.1 branch (meaning 2.1.5), I have not tested it on 2.1.4, but it might work. Since you have recompiled the source, you may have a different issue now, may you send another `adb logcat` please?

**Comment by Detor** [comment]
Hi, sorry for taking long to reply. Currently I cannot debug on an android device because my old laptop's usb stopped working :( 
I'll try my best to get to you once it's working again

**Comment by Detor** [comment]
Okay, so I tried again, this time I recompiled with the latest Godot 2.1 branch (as of 02 July 2018) and built it with Godot v2.1.5, but it still doesn't work. Here are two logs

[godot2.1.5rc1_1.adblogcat.txt](https://github.com/binogure-studio/godotamazon/files/2156835/godot2.1.5rc1_1.adblogcat.txt)
[godot2.1.5rc1_2.adblogcat.txt](https://github.com/binogure-studio/godotamazon/files/2156836/godot2.1.5rc1_2.adblogcat.txt)

**Comment by xsellier** [comment]
From the log file I can read that:

```
07-02 22:03:03.308  8438  8438 E GameCircleClient: Unable to read api key.  GameCircle requires an api key to be included in 'assets/api_key.txt'.  GameCircle will not initialize.
07-02 22:03:03.308  8438  8438 E GameCircleClient: java.lang.IllegalArgumentException: Invalid API Key
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.<init>(AmazonAuthorizationManager.java:126)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at com.amazon.ags.api.AmazonGamesClient.initialize(AmazonGamesClient.java:144)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at org.godotengine.godot.gamecircle.GameCircleClient.connect(GameCircleClient.java:108)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at org.godotengine.godot.gamecircle.GameCircleClient.onStart(GameCircleClient.java:91)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at org.godotengine.godot.GodotAmazonCommon.init(GodotAmazonCommon.java:15)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at org.godotengine.godot.GodotAmazon$1.run(GodotAmazon.java:96)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at android.os.Handler.handleCallback(Handler.java:751)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at android.os.Looper.loop(Looper.java:154)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-02 22:03:03.308  8438  8438 E GameCircleClient: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-02 22:03:03.311  8438  8438 W GameCircleClient: Amazon game is not ready due to CANNOT_INITIALIZE
```
'api_key.txt' has to be in the same folder as engine.cfg.
Don't forget to include this file when you export it.

**Comment by Detor** [comment]
Huh, but my api_key.txt is in my assets folder (beside the engine.cfg) and i got the api key from the amazon gamecircle game api, I'll reobtain the game's api key

**Comment by xsellier** [comment]
~~Here an example of the APK of Sneak In (an android game Im working on):~~

![image](https://user-images.githubusercontent.com/6616005/42187644-c33a8244-7e1e-11e8-85c6-7c2bba18f8af.png)

~~As you can notice, the `api_key.txt` file is in the `assets` directory in the APK, but it is in the root directory in the godot's project. Be sure that you are exporting it.~~

EDIT:

You are right there is another error later. It seems you fixed the issue with the `api_key.txt` file.

**Comment by Detor** [comment]
Here is mine
![screenshot from 2018-07-02 22-42-45](https://user-images.githubusercontent.com/17194678/42187813-551efa1c-7e49-11e8-9f0f-cbad995a47ce.png)
![screenshot from 2018-07-02 22-42-58](https://user-images.githubusercontent.com/17194678/42187815-5595f572-7e49-11e8-9dad-ad1db7cbaf39.png)
Maybe I am getting my api_key.txt at the wrong place could you show me where you got yours?

**Comment by xsellier** [comment]
@Detor You got it right.

Here the piece of code Im using to initialize Amazon. This file is a singleton loaded automatically by Godot when the game starts.

```python
extends Node

onready var godot_amazon = Globals.get_singleton('GodotAmazon')

var initialized = false

func _ready():
  if OS.get_name() == 'Android' and godot_amazon != null:
    call_deferred('_initialize')
  else:
    godot_amazon = null

func _initialize():
  godot_amazon.amazon_initialize(get_instance_ID())

  initialized = true
```

**Comment by xsellier** [comment]
@Detor From the first ADB logcat file the issue is:
`Unable to read api key.  GameCircle requires an api key to be included in 'assets/api_key.txt'.  GameCircle will not initialize.`

But from the second ADB logcat file I don't see this line:
`godot   : Loading module: org/godotengine/godot/GodotAmazon`

So I suppose that the second ADB logcat file is filtered, and I can't help with that.
Also use this command to filter the ADB logcat, otherwise I won't be able to help you.

```
adb logcat godot:* GodotAmazon:* InAppManager:* InAppPurchasingListener:* GameCircleAchievements:* GameCircleAuthentication:* GameCircleClient:* GameCircleLeaderboards:* GameCircleSnapshot:* *:S DEBUG:* AndroidRuntime:V ValidateServiceOp:V
```

**Comment by Detor** [comment]
I have the code just like that and it still crashes. 
I took a look at one of the logs and I found this:
`07-02 22:55:02.164 16390 16390 I com.amazon.identity.auth.device.appid.AbstractAppIdentifier: Finding API Key for com.dsguy.dodgeitlegacy
07-02 22:55:02.166 16390 16390 I com.amazon.identity.auth.device.utils.ThirdPartyResourceParser: Attempting to parse API Key from assets directory
07-02 22:55:02.172 16390 16390 I com.amazon.identity.auth.device.appid.APIKeyDecoder: Begin decoding API Key for packageName=com.dsguy.dodgeitlegacy
07-02 22:55:02.212 16390 16390 D com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: APIKey:<obscured>
07-02 22:55:02.214 16390 16390 I com.amazon.identity.auth.device.appid.APIKeyDecoder:  num sigs = 1
07-02 22:55:02.214 16390 16390 D com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Signature checking.:<obscured>
07-02 22:55:02.216 16390 16390 D com.amazon.identity.auth.device.appid.APIKeyDecoder.PII: Fingerpirint checking:<obscured>
07-02 22:55:02.220 16390 16390 W com.amazon.identity.auth.device.appid.APIKeyDecoder: Failed to decode: Decoding fails: certificate fingerprint can't be verified!
07-02 22:55:02.220 16390 16390 W com.amazon.identity.auth.device.appid.APIKeyDecoder: java.lang.SecurityException: Decoding fails: certificate fingerprint can't be verified!`
Could it be the fingerprint certficate error that could be causing the problem? If so, do you know how to set it up? Here's the filtered adb logcat, I hope it's not TMI
[godot2.1.5-rc1_5.adblogcat.txt](https://github.com/binogure-studio/godotamazon/files/2156956/godot2.1.5-rc1_5.adblogcat.txt)

**Comment by Detor** [comment]
I finally got it to work! The problem was because of how I was getting the `api_key.txt` :smile:
I was suppose to get the MD5 and SHA256 signature from my keystore file, not from the one amazon provided! Thanks for all the help!
